### ISSUE TITLE
Match addressing is wrong if the binary is analysed and sections mapped elsewhere

### ISSUE THREAD

**Issue by pyllyukko** [radareorg/r2yara#41]
So when I find a match, it expects the binary to start from `0x0`, but when the binary is analyzed with `-A` and e.g. `.text` section is mapped into `0x00401000` my match address is incorrect.

With `-n` it works correctly, as the binary is mapped from `0x0` onwards.

**Comment by trufae** [comment]
I think we should have a yara.va variable to choose that behaviour. Like io.va does but for yara search hits

**Comment by trufae** [comment]
Its not implemented i was suggesting to add an option for that

**Comment by pyllyukko** [comment]
> Its not implemented i was suggesting to add an option for that

Ah. I misunderstood. Sounds good.

**Comment by trufae** [comment]
wip https://github.com/radareorg/r2yara/pull/42

**Comment by trufae** [comment]
fixed in master

**Comment by pyllyukko** [comment]
> fixed in master

Thank you!

**Comment by pyllyukko** [comment]
Hmm. It doesn't seem to work properly.

If I do `r2 -A /bin/ls` and run `yrs` I get only this:

```
[0x00405340]> yrs
-> 0x403000 + 82729
```

With `r2 -n /bin/ls` it prints the hits properly and creates the flag(s).

**Comment by trufae** [comment]
See yara.in. Maybe we need to use io.maps as value by default
