### ISSUE TITLE
does not compile in windows: r2pm -U error on windows 10 : git not found

### ISSUE THREAD

**Issue by gogo2464** [radareorg/r2yara#8]
## Environment

```sh
> r2pm -ci r2yara
INFO: Cleaning r2yara
INFO: Using r2-5.8.8 and r2pm-5.8.8
ERROR: Please run r2pm -U to initialize/update the database
PS C:\PATH> r2pm -U
INFO: git clone --depth=10 --recursive https://github.com/radareorg/radare2-pm C:\Users\PATH\.local\share\\radare2\r2pm/git/radare2-pm
'git' is not recognized as a command
```

git --version
git version 2.43.0.windows.1

## Description

I would like to use r2yara on windows 10

**Comment by trufae** [comment]
The error have nothibg to do with r2yara. R2pm needs git to work. 

To make r2yara work on windows i would suggest you to submit support for meson

**Comment by trufae** [comment]
@sylvainpelissier wanna give it a try?

**Comment by trufae** [comment]
Closing here as its dupe for https://github.com/radareorg/r2yara/issues/13 where i try to collect all the required steps to achieve that thing. unfortunately installing yara on windows is not straighforward.
